language: node_js
addons:
  code_climate:
node_js:
  - "9.10.1"
install: yarn
script: yarn test
after_success:before_script: node_modules/.bin/tslint -c ./tslint.json './src/**/*.ts?(x)'
  - yarn global add codeclimate-test-reporter
  - codeclimate-test-reporter < ./coverage/lcov.info
